-- ANSWERS TO THE QUESTIONS
-- TO CREATE A TABLE, WE FIRST OF ALL CREATE A DATABASE CALLED school
-- QUESTION 1
CREATE TABLE student (
 id INT PRIMARY KEY AUTO_INCREMENT, fullName VARCHAR(100) NOT NULL,
 age INT 
);

--QUESTION 2
INSERT INTO student 
VALUES	(1, "MOHAMED SHUAIB", 28),
		    (2, "MOHAMED RASHID", 17),
        (3, "GEORGE Kagbeni", 28),
        (4, "REBECCA GBONDO", 26);

-- QUESTION 3
UPDATE STUDENT SET age = 20
WHERE id = 02;
